name = "llm-observability"
main = "dist/index.js"
compatibility_date = "2025-12-01"
type = "javascript"

[build]
command = "npm run build"
upload = { format = "service-worker", dir = "dist" }

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "llm_requests"
