name = "llm-router"
main = "dist/index.js"
compatibility_date = "2025-12-01"

[build]
command = "npm run build"

[env.staging]
name = "llm-router-staging"

[env.production]
name = "llm-router"

[[env.staging.kv_namespaces]]
binding = "MODEL_CATALOGUE"
id = "9736e521560746e29aaaec4b018097b9"

[[env.production.kv_namespaces]]
binding = "MODEL_CATALOGUE"
id = "39659a4d403045e7bcabb9b9610f387a"