name = "llm-gateway"
main = "dist/index.js"
compatibility_date = "2025-12-01"

[build]
command = "npm run build"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[[services]]
binding = "ROUTER"
service = "llm-router"

[[services]]
binding = "OBSERVABILITY"
service = "llm-observability"

[env.ci]
name = "llm-gateway-ci"

[env.ci.durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[env.ci.services]]
binding = "ROUTER"
service = "llm-router"

[[env.ci.services]]
binding = "OBSERVABILITY"
service = "llm-observability"

[env.staging]
name = "llm-gateway-staging"

[env.staging.ai]
binding = "AI"

[env.staging.durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[env.staging.services]]
binding = "ROUTER"
service = "llm-router-staging"

[[env.staging.services]]
binding = "OBSERVABILITY"
service = "llm-observability-staging"

[env.staging.vars]
JWT_ISSUER = "https://dev-aib8t0groa0n7v71.us.auth0.com/"
JWT_AUDIENCE = "https://llm-gateway"
AI_GATEWAY_ACCOUNT_ID = "f8cd483b056259da8aeb8817b2135da4"
AI_GATEWAY_ID = "llm-platform-staging"
AI_GATEWAY_CACHE_TTL = "300"

[[env.staging.kv_namespaces]]
binding = "PROMPT_REGISTRY"
id = "0408593d3ef44a91ad983d6f2400ebc1"



[env.production]
name = "llm-gateway"

[env.production.ai]
binding = "AI"

[env.production.durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[env.production.services]]
binding = "ROUTER"
service = "llm-router"

[[env.production.services]]
binding = "OBSERVABILITY"
service = "llm-observability"

[env.production.vars]
JWT_ISSUER = "https://dev-aib8t0groa0n7v71.us.auth0.com/"
JWT_AUDIENCE = "https://llm-gateway"
AI_GATEWAY_ACCOUNT_ID = "f8cd483b056259da8aeb8817b2135da4"
AI_GATEWAY_ID = "llm-platform-production"
AI_GATEWAY_CACHE_TTL = "300"

[[env.production.kv_namespaces]]
binding = "PROMPT_REGISTRY"
id = "6a368deb93384096906642b2787c324a"